apiVersion: apps/v1
kind: Deployment
metadata:
  name: gobgp-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gobgp-router
  template:
    metadata:
      labels:
        app: gobgp-router
    spec:
      containers:
        - name: gobgp-router
          image: majedur708/hlf-api:300.120
          ports:
            - containerPort: 50051   
            - containerPort: 50052   
            - containerPort: 50053   
            - containerPort: 50054   
            - containerPort: 50055  
            - containerPort: 50056   
            - containerPort: 50057
            - containerPort: 50058
            - containerPort: 50059
            - containerPort: 50060
            - containerPort: 50061
            - containerPort: 50062
            - containerPort: 50063
            - containerPort: 50064
            - containerPort: 50065
            - containerPort: 50066
            - containerPort: 50067
            
          resources:
            requests:
              memory: "250Mi"
              cpu: "200m"
            limits:
              memory: "350Mi"
              cpu: "300m"          
          securityContext:
            runAsUser: 0
            capabilities:
              add: ["NET_ADMIN", "NET_BIND_SERVICE"]

---
apiVersion: v1
kind: Service
metadata:
  name: gobgp-service
spec:
  selector:
    app: gobgp-router
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
    - name: grpc
      port: 50052
      targetPort: 50052
    - name: grpc
      port: 50053
      targetPort: 50053
    - name: grpc
      port: 50054
      targetPort: 50054
    - name: grpc
      port: 50055
      targetPort: 50055
    - name: grpc
      port: 50056
      targetPort: 50056
    - name: grpc
      port: 50057
      targetPort: 50057
    - name: grpc
      port: 50058
      targetPort: 50058
    - name: grpc
      port: 50059
      targetPort: 50059
    - name: grpc
      port: 50060
      targetPort: 50060
    - name: grpc
      port: 50061
      targetPort: 50061
    - name: grpc
      port: 50062
      targetPort: 50062
    - name: grpc
      port: 50063
      targetPort: 50063
    - name: grpc
      port: 50064
      targetPort: 50064
    - name: grpc
      port: 50065
      targetPort: 50065
    - name: grpc
      port: 50066
      targetPort: 50066
    - name: grpc
      port: 50067
      targetPort: 50067
      protocol: TCP
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gobgp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gobgp-api
  template:
    metadata:
      labels:
        app: gobgp-api
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mypvc
      containers:
        - name: gobgp-api
          image: majedur708/hlf-api:50.38
          ports:
            - containerPort: 2000
          env:
            - name: GOBGPD_ADDR
              value: "gobgp-service:50051"
          resources:
            requests:
              memory: "250Mi"
              cpu: "200m"
            limits:
              memory: "350Mi"
              cpu: "300m"
          volumeMounts:
            - name: data
              mountPath: /usr/src/app/connection-profile
              subPath: connection-profile
            - name: data
              mountPath: /organizations
              subPath: organizations

---
apiVersion: v1
kind: Service
metadata:
  name: gobgp-api
spec:
  selector:
    app: gobgp-api
  ports:
    - name: http
      port: 2000
      targetPort: 2000
      protocol: TCP
  type: ClusterIP



